FROM node:18

RUN yarn cache clean

WORKDIR /app

COPY .yarn .yarn
COPY .yarnrc.yml .

COPY package.json yarn.lock .

COPY web/package.json ./web/

RUN yarn install

COPY . .

# prerendering repends on having a db up - @rainkinz
RUN yarn rw build web --prerender false

CMD ["yarn", "rw", "serve", "web", "--apiHost http://api-serve:8911"]
