version: "3.9"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  web:
    build:
      context: ../../
      dockerfile: ./Dockerfiles/leftlane-mmentele-example/web/Dockerfile
      target: publish
    environment:
      - APISERVER_SERVICE=api
    ports:
      - "8910:8910"
  api:
    volumes:
      - .env:/home/apiuser/.env
    build:
      context: ../../
      dockerfile: ./Dockerfiles/leftlane-mmentele-example/Dockerfile
    ports:
      - "8911:8911"
    entrypoint: yarn rw dev api
